### ISSUE TITLE
Whatsapp mod

### ISSUE THREAD

**Issue by Deleora** [vishwakarma-anshu/whatsapp_clone_app#1]
Apart from UI are there any plans to make this as a modded client for official whatsapp?

**Comment by vishwakarma-anshu** [comment]
No i'm just trying to learn Flutter Language. I even don't know if it's
legal to do so. I thought it would be cool to see how far can i make the
app look similar to the real one using Flutter for UI and Firestore for
Database.

**Comment by Deleora** [comment]
Well, from my research creating modded clients isn't illegal (at least that's what XDA says).
Anyway, good luck!! 😎👍👍
